packages:
  - services/*
  - webapp
  - shared
  - apps/*
  - worker
  - packages/*
  - packages/ml-core

ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - argon2
  - esbuild
  - prisma
