packages:
  - services/*
  - domain/*
  - webapp
  - shared
  - apps/*
  - worker
  - packages/*

ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - argon2
  - esbuild
  - prisma
