ALTER TABLE "Organization"
ADD COLUMN IF NOT EXISTS "onboardingComplete" BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE "Organization"
ALTER COLUMN "onboardingComplete" SET DEFAULT FALSE;

ALTER TABLE "Org"
ADD COLUMN IF NOT EXISTS "onboardingComplete" BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE "Org"
ALTER COLUMN "onboardingComplete" SET DEFAULT FALSE;
