// apps/phase1-demo/src/prisma-shim.d.ts
// Lightweight shim so the demo app can compile even if these
// types aren't generated by the current Prisma schema.

declare module "@prisma/client" {
  /**
   * Minimal PrismaClient shape to satisfy JournalWriter's PrismaJournalClient.
   * Runtime still uses the real Prisma client from node_modules; this is
   * only about TypeScript seeing the right structure.
   */
  export class PrismaClient {
    journal: {
      findFirst(args: any): Promise<any>;
      create(args: any): Promise<any>;
    };

    $transaction<T>(fn: (tx: PrismaClient) => Promise<T>): Promise<T>;

    // Allow any other properties/methods without strict typing.
    [key: string]: any;
  }

  /**
   * AccountType/AccountSubtype as both values and types so you can write:
   *   type: AccountType.ASSET
   *   subtype: AccountSubtype.BANK
   */

  export const AccountType: {
    ASSET: "ASSET";
    LIABILITY: "LIABILITY";
    EXPENSE: "EXPENSE";
  };

  export type AccountType = (typeof AccountType)[keyof typeof AccountType];

  export const AccountSubtype: {
    BANK: "BANK";
    PAYGW_BUFFER: "PAYGW_BUFFER";
    GST_BUFFER: "GST_BUFFER";
    CLEARING: "CLEARING";
    SUSPENSE: "SUSPENSE";
  };

  export type AccountSubtype = (typeof AccountSubtype)[keyof typeof AccountSubtype];
}
