name: Evidence Backup

on:
  schedule:
    - cron: "30 2 * * *"
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Start API Gateway
        run: |
          pnpm --filter @apgms/api-gateway dev &
          echo $! > gateway.pid

      - name: Wait for readiness
        run: |
          for i in {1..30}; do
            if curl -sf http://localhost:3000/ready > /dev/null; then
              exit 0
            fi
            sleep 2
          done
          echo "API gateway failed to become ready" >&2
          kill $(cat gateway.pid)
          exit 1

      - name: Acquire JWT
        id: login
        run: |
          TOKEN=$(curl -sf -X POST http://localhost:3000/auth/login \
            -H 'Content-Type: application/json' \
            -d '{"email":"dev@example.com","password":"admin123"}' | jq -r '.token')
          if [ -z "$TOKEN" ] || [ "$TOKEN" = "null" ]; then
            echo "Failed to obtain token" >&2
            exit 1
          fi
          echo "token=$TOKEN" >> "$GITHUB_OUTPUT"

      - name: Generate evidence pack
        env:
          APGMS_API_TOKEN: ${{ steps.login.outputs.token }}
        run: |
          pnpm backup:evidence-pack -- \
            --base-url http://localhost:3000 \
            --org dev-org \
            --token "${APGMS_API_TOKEN}" \
            --out artifacts/evidence

      - name: Stop API Gateway
        if: always()
        run: kill $(cat gateway.pid) || true

      - name: Upload evidence artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: compliance-evidence-pack
          path: artifacts/evidence/*.json
